sample_transcript = """
Provider: "Hello Ms. Smith. Your doctor requested a urology consult to see if you have an obstructing kidney stone or if you need any interventions. How are you feeling today? "
Patient: "OK. I'm still having low back pain on my right side that hurts more when I move."
Provider: "How would you describe the pain? Sharp? Dull? Cramp-like? On a scale of 1 to 10?"
Patient: "It's a dull pain and it's probably about a 7."
Provider: "Is the pain traveling anywhere else on your body?"
Patient: "No. Just in my lower back."
Provider: "Are you having any pain when you pee?"
Patient: "Yes."
Provider: "Are you having to pee often? More often than normal?"
Patient: "Yes."
Provider: "Do you see any blood when you pee?"
Patient: "No, no blood."
Provider: "Are you feeling nauseous? Have you had to vomit?"
Patient: "No."
Provider: "Have you ever had kidney stones before?"
Patient: "No, not that I know of."
Provider: "Have you ever had a UTI before?"
Patient: "No."
Provider: "Do you take any medications?"
Patient: "I take Enalapril."
Provider: "Is that to treat your high blood pressure?"
Patient: "Yes, I think so."
Provider: "Do you know the dosage?"
Patient: "I think 30 mg."
"""